add git configuration file

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -2,6 +2,9 @@
 #
 # Perform the initial configuration/installs for the system
 
+# exit if anything fails
+set -e
+
 # cd into dotfiles directory
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT=$(pwd -P)
@@ -9,5 +12,42 @@ DOTFILES_ROOT=$(pwd -P)
 # import functions
 source functions/index.sh
 
-# exit if anything fails
-set -e
+function setupGitConfig() {
+	if ! [ -f git/gitconfig.symlink ]
+	then
+		logInfo 'setup gitconfig'
+
+		credentialHelper='cache'
+		if [ isMacOs ]
+		then
+			credentialHelper='osxkeychain'
+		fi
+
+		# get the user's credentials
+		logQuestion ' - What is your github author name?'
+		read -e git_authorname
+		logQuestion ' - What is your github author email?'
+		read -e git_authoremail
+
+		# copy contents of gitconfig.symlink.example and replace values with the ones provided above
+		sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$credentialHelper/g" git/gitconfig.symlink.example > git/gitconfig.symlink
+
+		logSuccess 'gitconfig'
+	fi
+}
+
+function configureSymlinkFiles() {
+	logInfo 'configure symlink files'
+
+	local overrideMode=
+	# iterate through symlink files
+	for source in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+	do
+		# add a '.' to the front remove the .symlink extension from the end of the file name
+		destination="$HOME/.$(basename "${source%.*}")"
+		linkFile "$source" "$destination" overrideMode
+	done
+}
+
+setupGitConfig
+configureSymlinkFiles
